#!/bin/bash


List_IP=("10.181.178.217" "10.181.172.130" "10.154.134.26" "10.154.134.170")

for addr in "${List_IP[@]}"
do
    echo $addr
    sshpass -p 'b4meshroot' scp default@$addr:/var/persistent-data/b4mesh/blockgraph* Results
    sshpass -p 'b4meshroot' scp default@$addr:/var/persistent-data/b4mesh/mempool* Results
done
