#!/bin/bash
# dependance graphviz
# exec txt2Png srcfile pngfile
# $./txt2Png blockgraph-0.txt res.png

awk 'BEGIN { print "digraph {\nrankdir=LR;" } { if($1 != "#BlockGroup" && $1 != "0") {print $2 " -> " $3 " [label=\"" $1 "\"];"} } END{ print "}" }' $1 > graph
dot -Tpng ./graph > $2
rm graph
