name: cmake-green-toolchain_default-env

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    # todo : matrix (linux only)

    steps:
    # Use default cmake, default generator, default builder
    - uses: actions/checkout@v2

    # libboost-all-dev \
    - name: Install required dependencies packages
      run : |
          sudo apt update && sudo apt install libboost-dev \
              libboost-filesystem-dev \
              libboost-random-dev \
              libboost-system-dev

    - name: CMake cache generation
      run: cmake -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/build/output -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target greensoftsdk
