name: cmake-green-toolchain_default-env

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    # todo : matrix (linux only)

    steps:
    # Use default cmake, default generator, default builder
    - uses: actions/checkout@v2

    # libboost-all-dev \
    - name: Install required dependencies packages
      run : |
          sudo apt update && sudo apt install libboost-dev \
              libboost-filesystem-dev \
              libboost-random-dev \
              libboost-system-dev

    - name: Creating CMake directories (cache, install)
      run: mkdir -p ${{github.workspace}}/out/build && mkdir -p ${{github.workspace}}/out/build

    # todo : validate -G "Ninja" instead of default "Unix-Makefile"
    - name: toolchain - CMake cache generation
      run: |
        cmake \
            -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} \
            -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install \
            -S ${{github.workspace}} \
            -B ${{github.workspace}}/out/build

    - name: toolchain - CMake build
      run: |
        cmake \
            --build ${{github.workspace}}/out/build \
            --config ${{env.BUILD_TYPE}} \
            --target greensoftsdk

    - name: toolchain - post build cache cleaning
      run: rm -rf ${{github.workspace}}/out/build/*

    - name: project - CMake cache generation
      run: |
        cmake \
            -DCMAKE_BUILD_TYPE:STRING="Release" \
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH="${{github.workspace}}/out/install/toolchain/greensoftsdk/share/buildroot/toolchainfile.cmake" \
            -Dremote_machines_IP:STRING="10.181.178.217;10.181.172.130;10.154.134.26;10.154.134.170;10.181.178.210" \
            -Dremote_install_dir:PATH="/var/persistent-data/b4mesh" \
            -Db4mesh_USE_CLANG_TIDY:BOOL=OFF \
            -S ${{github.workspace}} \
            -B ${{github.workspace}}/out/build

    - name: project - CMake build
      run: |
        cmake \
            --build ${{github.workspace}}/out/build \
            --config ${{env.BUILD_TYPE}}


    - name: project - CMake install
      run: cmake --install ${{github.workspace}}/out/build
