function(GreenSDK_Toolchain_lazyDetection)

    if (${CMAKE_TOOLCHAIN_FILE} MATCHES ".*\/greensoftsdk\/.*\/toolchainfile\.cmake$")
        if (NOT (EXISTS ${CMAKE_TOOLCHAIN_FILE}))
            message(FATAL_ERROR "[toolchain/lazy_detection] : toolchain required but not found. Run greensoftsdk target first to generate it")
        endif()
        set(USING_GREEN_SDK ON CACHE BOOL "GreenSDK toolchain autodetection" FORCE)
    else()
        set(USING_GREEN_SDK OFF CACHE BOOL "GreenSDK toolchain autodetection" FORCE)
    endif()
    message(STATUS "[toolchain/lazy_detection] : Lazy Green SDK detection ... USING_GREEN_SDK is [${USING_GREEN_SDK}]")
endfunction()